import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import NavMenu from "@/components/share/navigation-menu";
import Header from "@/components/share/header";
import Footer from "@/components/share/footer";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="flex flex-col gap-[32px]">
          <Header />
          <section className="py-32">
            <div className="container mx-auto">
            {children}
            </div>
           </section>
          <Footer/>
        </main>
      </body>
    </html>
  );
}
